language: php

php:
  - 7.3
  - 7.4

sudo: false

install:
  - travis_retry composer install --no-interaction

services:
    - docker
env:
  global:
    - IMAGE_NAME=namelivia/trajon
before_script:
  - php artisan test
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true
    branch: master
after_script:
- bash <(curl -s https://codecov.io/bash)
